### ISSUE TITLE
When can the code be released?

### ISSUE THREAD

**Issue by HaoZhang16613** [MasterHow/CoBEV#1]
Hi~ impressive work! Wanted to know when will you release the code?
Thanks！

**Comment by MasterHow** [comment]
Thanks for your interest! We will organize the code after our paper revision if everything goes well.

**Comment by dFuong** [comment]
Can you release code as soon as possible ?

**Comment by lacie-life** [comment]
When are you planning to release the code?
Thanks!

**Comment by NoctisJOJO** [comment]
one years later~

**Comment by MasterHow** [comment]
Hi, the code and pretrianed models are released now, thanks for your attention~ =)
